### ISSUE TITLE
Add a dev branch and start tagging releases inline with Vlad

### ISSUE THREAD

**Issue by dixhuit** [hashbangcode/vlad-docs#1]
Hopefully the issue title says it all. I'm guessing this is the best workflow for matching docs against different Vlad releases / branches? Correct me if I'm wrong :)

**Comment by dixhuit** [comment]
Woah! There is a dev branch! :D 

OK, let's just start tagging releases then...

**Comment by philipnorton42** [comment]
:+1:

**Comment by dixhuit** [comment]
Have now rebased dev to be up to date with master. I see you've added a tag.

**Comment by philipnorton42** [comment]
Quite right :)

So I've tagged the latest version (1.0.3) and added the config to readthedocs to allow for the different versions to be viewed.

**Comment by dixhuit** [comment]
Cool. Closing.
