### ISSUE TITLE
Update docs to add ~/.ssh/config file

### ISSUE THREAD

**Issue by xaviemirmon** [hashbangcode/vlad-docs#10]
The docs are outdated have caused me some confusion.   

We need to add some documentation for adding a ~/.ssh/config file

with:

`Host *.local
  ForwardAgent yes`

So that the vagrant box will pickup the host's SSH key if the use_host_id: true is selected.

**Comment by philipnorton42** [comment]
I've added a note to this effect, but I will be revisiting the entire docs repo over the next few weeks so if there is anything that you want added (or you think more information is needed) then please let us know :)
