### ISSUE TITLE
Error when trying to run custom playbook without a full provision.

### ISSUE THREAD

**Issue by mvance** [hashbangcode/vlad-docs#12]
When trying to follow the documentation, I was getting an error when trying to run just my custom playbook without a full `vagrant provision`:

```
$ ansible-playbook -i vlad_guts/host.ini --private-key=~/.vagrant.d/insecure_private_key ../vlad_custom/provision.yml

PLAY [Custom VLAD tools setup] ************************************************

GATHERING FACTS ***************************************************************
fatal: [192.168.9.24] => SSH Error: Permission denied (publickey,password).
    while connecting to 192.168.9.24:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [Tools | Clear all caches.] *********************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/me/provision.retry

192.168.9.24               : ok=0    changed=0    unreachable=1    failed=0
```

After looking at the [vlad-play.sh](https://github.com/hashbangcode/vlad/blob/master/vlad_guts/scripts/vlad-play.sh), I realized that adding `-u vagrant` seems to necessary. I'll follow up with a pull request shortly.

**Comment by dixhuit** [comment]
Do you specify a user at the top of your custom playbook's main YAML file?

A bit like: https://github.com/danbohea/vlad_custom/blob/master/provision.yml

**Comment by mvance** [comment]
@danbohea No, I haven't been doing that, but I'll try it. Thanks for the suggestion.

I still think it would be worthwhile to update the documentation though, since you either need to know to designate the user in the YAML file or on the command line. For what it's worth, during development I wasted way too much time rerunning the full VLAD + custom playbook provisioning, before finally figuring out why I wasn't able to run just the custom playbook. My hope with the documentation change is to help save someone else that time and/or frustration.

**Comment by dixhuit** [comment]
Fair enough. Merged :)
