### ISSUE TITLE
Catch up with changes in Vlad 1.1.6

### ISSUE THREAD

**Issue by dixhuit** [hashbangcode/vlad-docs#15]
The master branch of the docs is now behind Vlad's master branch.

All of the changes that went in the the recent "galaxy" branch were merged into dev a while back, this means that stuff is now in Vlad 1.1.6 but I see no mention of any of it in the release notes.

Stuff that needs to be covered (and quick):
- `pantheon_cli_install`
- `aberdeen_cli_install`
- `drush_composer_path`
- `drush_install_path`
- `drush_keep_updated`
- `drush_path`
- `drush_version`
- `drush_install_commands`
- Local settings files now always use the "vlad_" prefix https://github.com/hashbangcode/vlad/commit/1ee836d2eafaf1258f2bd106ff94093fa5ae816d
- `vlad_db_dump_on_halt_destroy`
- `vlad_drupal_install`
- `vlad_drupal_install_version`

DON'T PANIC!!! :)

**Comment by philipnorton42** [comment]
Crud :(
I've been too busy to keep much of an eye on Vlad recently so I've missed these being added. Looking over the docs was also on my to-do list going forward.
Thanks for this list though @danbohea, it really helps!

**Comment by dixhuit** [comment]
DON'T PANIIIIIIC!!!

**Comment by dixhuit** [comment]
--> https://github.com/hashbangcode/vlad-docs/issues/11 <--

**Comment by dixhuit** [comment]
I've just pushed commits directly to the master branch that aim to tackle this. Their not ideal but they're certainly an improvement on no docs at all :)

I've also merged master back into to dev to keep everything sweet.

**Comment by dixhuit** [comment]
Balls. I haven't updated the changelog...

**Comment by dixhuit** [comment]
Sorted.
