### ISSUE TITLE
Add more links between docsite and Vlad

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad-docs#3]
The Vlad documentation site needs more information about where to get Vlad from. Some more 'Get it here!' links on the home page might be nice. Perhaps a styled 'Download' button? (if possible)

Do you think the "Edit on GitHub" link at the top should point at the Vlad repo or the Docs repo?

**Comment by dixhuit** [comment]
> Do you think the "Edit on GitHub" link at the top should point at the Vlad repo or the Docs repo?

Defo the docs repo.

**Comment by philipnorton42** [comment]
Ok. I've done the main link.

Turns out I also committed this directly to the master branch. Never mind, at least it's relevant information :)

**Comment by dixhuit** [comment]
> Turns out I also committed this directly to the master branch. Never mind, at least it's relevant information :)

At least you didn't delete the repo! :D

**Comment by philipnorton42** [comment]
All done :)
